package pl.michalrola._3_MethodsCommonToAllObjects.Item10_equals._3_Transitive;

import java.awt.Color;
import java.util.Objects;

public class ColorPoint {

  private final Point point;
  private final Color color;

  public ColorPoint(Point point, Color color) {
    this.point = point;
    this.color = color;
  }

  //returns point view of color point
  public Point asPoint() {
    return point;
  }

  @Override
  public boolean equals(Object obj) {
    if (!(obj instanceof ColorPoint)) {
      return false;
    }
    ColorPoint colorPoint = (ColorPoint) obj;
    return colorPoint.point.equals(point) &&
        colorPoint.color.equals(color);
  }

  //autogenerated by IDE
//  @Override
//  public boolean equals(Object o) {
//    if (this == o) {
//      return true;
//    }
//    if (o == null || getClass() != o.getClass()) {
//      return false;
//    }
//    ColorPoint that = (ColorPoint) o;
//    return point.equals(that.point) &&
//        color.equals(that.color);
//  }

  @Override
  public int hashCode() {
    return Objects.hash(point, color);
  }
}
